depth = 4
#depth of search
player1 = 0
#Player type:
#0: You 
#1: Random
#2: AI
player2 = 2
#Player type:
#0: You
#1: Random
#2: AI
rounds = 1
#rounds of game (set higher for automated games)
printAlpha = 1
#print alpha Value of first MaxValue function (indicator on how sure to win the AI is)
#1: print Alpha Value
#0: Do not print Alpha Value